apiVersion: batch/v1
kind: CronJob
metadata:
  name : busybox-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox-cronjob
              image: busybox
              command: ["echo", "Hello Cronjob"]
          restartPolicy: "Never"

